### ISSUE TITLE
Lock down permissions to GitHub environments

### ISSUE THREAD

**Issue by samkio** [samkio/repo-sandbox#4]
As seen here https://www.eliasbrange.dev/posts/secure-aws-deploys-from-github-actions-with-oidc/
The IAM role can be specified to a certain environment meaning we can use protection rules in GitHub to ensure that the role is assumed when required.

**Comment by samkio** [comment]
```
Parameters:
  GitHubOrg:
    Type: String
  RepositoryName:
    Type: String
  EnvironmentName:
    Default: ''
    Type: String
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider.
    Default: ''
    Type: String
Conditions:
  CreateOIDCProvider: !Equals 
    - Ref: OIDCProviderArn
    - ''
  UseEnvironment: !Equals 
    - Ref: EnvironmentName
    - ''
Resources:
  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: 'sts:AssumeRoleWithWebIdentity'
            Principal:
              Federated: !If 
                - CreateOIDCProvider
                - !Ref GithubOidc
                - !Ref OIDCProviderArn
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub': !If 
                  - UseEnvironment
                  - !Sub >-
                    repo:${GitHubOrg}/${RepositoryName}:environment:${EnvironmentName}
                  - !Sub 'repo:${GitHubOrg}/${RepositoryName}:*'
      Policies:
        - PolicyName: CDKAssumeRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/cdk-*
  GithubOidc:
    Type: 'AWS::IAM::OIDCProvider'
    Condition: CreateOIDCProvider
    Properties:
      Url: 'https://token.actions.githubusercontent.com'
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
Outputs:
  Role:
    Value: !GetAtt Role.Arn
```
